version: '3.7'
services:
    mysite01:
        shm_size: '1000000000'
        build:
            context: ./mysite/app
        tty: true
        volumes:
            - './mysite/app/src:/home/ubuntu'
    mysite02:
        shm_size: '1000000000'
        build:
            context: ./mysite/app
        tty: true
        volumes:
            - './mysite/app/src:/home/ubuntu'
    nginx:
        build: ./mysite/nginx
        tty: true
        links:
            - mysite01
            - mysite02

        ports:
            - '80:80'

