version: '3.7'
services:
    mysite01:
        shm_size: '1000000000'
        image: tonytheleg/mysite-flask 
    mysite02:
        image: mysite-flask    
    nginx:
        image: tonytheleg/mysite-nginx 
        links:
            - mysite01
            - mysite02

        ports:
            - '80:80'

